Huge update
Now only shows information for testing that fails

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -8,4 +8,24 @@ export TESTS=$(find * -type f -follow -print | sed 's/\//\./g' | sed 's/.java//g
 cd "$DIR"
 
 make test_compile
-make $TESTS
+
+STATUS=$?
+if (( $STATUS != 0 )); then
+  make clean 1>/dev/null
+  echo -e "\nThere was an error in compilation. Tests will not run.\n---------------------------------\n"
+  exit $STATUS
+fi
+
+echo
+for i in $TESTS; do
+  TEST_DATA=$(make $i)
+
+  STATUS=$?
+  if (( $STATUS != 0 )); then
+    LINE_COUNT=$(echo "$TEST_DATA" | wc -l)
+    LINE_COUNT=$((LINE_COUNT - 4))
+    echo -e "\nThere was an error in testing $i.\n---------------------------------\n$(echo "$TEST_DATA" | tail -n $LINE_COUNT)\n"
+  else
+    echo -e "Test:\t$i passed"
+  fi
+done
